spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/rshiva777/argocd.git
    targetRevision: main
applicationSet:
  image:
    repository: quay.io/argoproj/argocd-applicationset      
